version: '3.2'

networks:
  template:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=serverless
    ports:
      - 3306:3306
    networks:
      - template