service: clean-arch-sls

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

custom:
  functionsDir: src/4-framework/functions
  serverless-offline:
    httpPort: 3333
  serverless-webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    excludeFiles: tests/**

plugins:
  - serverless-webpack
  - serverless-offline

# For more legible yml, try to spread the routes in different files
# https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-properties-in-other-files
functions:
  - ${file(${self:custom.functionsDir}/users/users.yml)}
  - ${file(${self:custom.functionsDir}/authentication/auth.yml)}
  - ${file(${self:custom.functionsDir}/roles/roles.yml)}
  - ${file(${self:custom.functionsDir}/hello/hello.yml)}